FROM node:14

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package*.json ./

RUN npm install

COPY . .

ENTRYPOINT ["/app/dev-entrypoint.sh"]

EXPOSE 8080

CMD ["npm", "run", "start:dev"]
