name: Build docker

on:
  push: 
    branches:
      - "*"
  pull_request:
    branches: [master, develop]

jobs:

  Front-end:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker-compose-dev image
      run: docker-compose -f client/docker-compose.dev.yml up -d
    
    - name: Run project's linter
      run: docker-compose -f  client/docker-compose.dev.yml exec -T app-dev npm run lint
    


