name: Test

on:
  push: 
    branches:
      - "master"
  pull_request:
    branches: [master, develop]

jobs:

  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Initialize project's environment
      run: ./init_env_dev.sh

    - name: Import data
      run: docker-compose -f docker-compose.dev.yml exec -T db-dev mongoimport --host db-dev --db ${{ secrets.DB_NAME }} --authenticationDatabase admin --username ${{ secrets.DB_USER }} --password ${{ secrets.DB_PASSWORD }} --collection user --drop --type json --file docker-entrypoint-initdb.d/init-mongo/user.json --jsonArray
    
    - name: Check running containers
      run: docker ps -a

    - name: Run project's test
      run: docker-compose -f docker-compose.dev.yml run -T cypress npx cypress run
